version: '3.2'
services:
  minio:
    image: minio/minio
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key


    ports:
      - "9000:9000"
    command: "server /data"
